#!/bin/bash

# To enable python to discover tests, test files should be named
# test*.py and be located in a directory that includes an __init__.py
# file.

# For the test*.py files to be able to import the modules correctly,
# you should either run this command from the project root directory,
# or else set the PYTHONPATH environment variable to the project's
# root directory.

# Example of running all tests for a specific module:
#python -m unittest -v qsc.tests.test_newton

# Example of running a specific test that matches a pattern:
#python -m unittest -v qsc.tests.test_grad_B_tensor.GradGradBTensorTests -k axisymm
#python -m unittest -v qsc.tests.test_spectral_diff_matrix -k Fourier

# Run all tests:
python -m unittest -v
# -v for verbose
